# Generated by Django 3.2.7 on 2021-11-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='actores',
        ),
        migrations.RenameModel(
            old_name='Actor',
            new_name='Alumno',
        ),
        migrations.DeleteModel(
            name='Actuacion',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(through='pelicula.Asignacion', to='pelicula.Alumno'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.alumno'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.curso'),
        ),
    ]
